### ISSUE TITLE
not able to start local system apps like in old version

### ISSUE THREAD

**Issue by kafos** [jisse44/ipprotocols#1]
with the new version firefox is only trying to open a url. How is it possible to start lokal installed applikations like it was possible in the old version??

**Comment by jisse44** [comment]
Hi,
Which OS do you have?
If Windows you need to register the protocols with .reg file in Windows section (see README-Windows.txt)
For Windows or Linux, you need to create a script, like the ones i give in example.

For me it's not an issue, have you read the HOWTO.txt ?
